// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello_http/hello_http.proto

/*
Package hello_http is a generated protocol buffer package.

It is generated from these files:
	hello_http/hello_http.proto

It has these top-level messages:
	HelloHTTPRequest
	HelloHTTPResponse
*/
package hello_http

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/jergoo/go-grpc-example/proto/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HelloRequest 请求结构
type HelloHTTPRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloHTTPRequest) Reset()                    { *m = HelloHTTPRequest{} }
func (m *HelloHTTPRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloHTTPRequest) ProtoMessage()               {}
func (*HelloHTTPRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloHTTPRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// HelloResponse 响应结构
type HelloHTTPResponse struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloHTTPResponse) Reset()                    { *m = HelloHTTPResponse{} }
func (m *HelloHTTPResponse) String() string            { return proto.CompactTextString(m) }
func (*HelloHTTPResponse) ProtoMessage()               {}
func (*HelloHTTPResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloHTTPResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloHTTPRequest)(nil), "hello_http.HelloHTTPRequest")
	proto.RegisterType((*HelloHTTPResponse)(nil), "hello_http.HelloHTTPResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HelloHTTP service

type HelloHTTPClient interface {
	// 定义SayHello方法
	SayHello(ctx context.Context, in *HelloHTTPRequest, opts ...grpc.CallOption) (*HelloHTTPResponse, error)
}

type helloHTTPClient struct {
	cc *grpc.ClientConn
}

func NewHelloHTTPClient(cc *grpc.ClientConn) HelloHTTPClient {
	return &helloHTTPClient{cc}
}

func (c *helloHTTPClient) SayHello(ctx context.Context, in *HelloHTTPRequest, opts ...grpc.CallOption) (*HelloHTTPResponse, error) {
	out := new(HelloHTTPResponse)
	err := grpc.Invoke(ctx, "/hello_http.HelloHTTP/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloHTTP service

type HelloHTTPServer interface {
	// 定义SayHello方法
	SayHello(context.Context, *HelloHTTPRequest) (*HelloHTTPResponse, error)
}

func RegisterHelloHTTPServer(s *grpc.Server, srv HelloHTTPServer) {
	s.RegisterService(&_HelloHTTP_serviceDesc, srv)
}

func _HelloHTTP_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloHTTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloHTTPServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello_http.HelloHTTP/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloHTTPServer).SayHello(ctx, req.(*HelloHTTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloHTTP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello_http.HelloHTTP",
	HandlerType: (*HelloHTTPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloHTTP_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello_http/hello_http.proto",
}

func init() { proto.RegisterFile("hello_http/hello_http.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0x8f, 0xcf, 0x28, 0x29, 0x29, 0xd0, 0x47, 0x30, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0xb8, 0x10, 0x22, 0x52, 0x32, 0xe9, 0xf9, 0xf9, 0xe9, 0x39, 0xa9, 0xfa, 0x89, 0x05, 0x99, 0xfa,
	0x89, 0x79, 0x79, 0xf9, 0x25, 0x89, 0x25, 0x99, 0xf9, 0x79, 0xc5, 0x10, 0x95, 0x4a, 0x6a, 0x5c,
	0x02, 0x1e, 0x20, 0xb5, 0x1e, 0x21, 0x21, 0x01, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42,
	0x42, 0x5c, 0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6,
	0x92, 0x2e, 0x97, 0x20, 0x92, 0xba, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21, 0x09, 0x2e, 0xf6,
	0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0x74, 0x98, 0x5a, 0x18, 0xd7, 0x28, 0x8f, 0x8b, 0x13, 0xae, 0x5c,
	0x28, 0x91, 0x8b, 0x23, 0x38, 0xb1, 0x12, 0xcc, 0x17, 0x92, 0xd1, 0x43, 0x72, 0x2c, 0xba, 0xcd,
	0x52, 0xb2, 0x38, 0x64, 0x21, 0xf6, 0x29, 0x49, 0x34, 0x5d, 0x7e, 0x32, 0x99, 0x49, 0x48, 0x89,
	0x57, 0x3f, 0xb5, 0x22, 0x31, 0xb7, 0x20, 0x27, 0x55, 0x3f, 0x35, 0x39, 0x23, 0xdf, 0x8a, 0x51,
	0xcb, 0x89, 0x27, 0x0a, 0xc9, 0xcb, 0x49, 0x6c, 0x60, 0xbf, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xae, 0xe5, 0xf0, 0x95, 0x24, 0x01, 0x00, 0x00,
}
