// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello_http/hello_http.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	hello_http/hello_http.proto

It has these top-level messages:
	HelloHttpRequest
	HelloHttpReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/jergoo/go-grpc-example/proto/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

// HelloRequest 请求结构
type HelloHttpRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloHttpRequest) Reset()                    { *m = HelloHttpRequest{} }
func (m *HelloHttpRequest) String() string            { return proto1.CompactTextString(m) }
func (*HelloHttpRequest) ProtoMessage()               {}
func (*HelloHttpRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloHttpRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// HelloReply 响应结构
type HelloHttpReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloHttpReply) Reset()                    { *m = HelloHttpReply{} }
func (m *HelloHttpReply) String() string            { return proto1.CompactTextString(m) }
func (*HelloHttpReply) ProtoMessage()               {}
func (*HelloHttpReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloHttpReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*HelloHttpRequest)(nil), "proto.HelloHttpRequest")
	proto1.RegisterType((*HelloHttpReply)(nil), "proto.HelloHttpReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HelloHttp service

type HelloHttpClient interface {
	// 定义SayHello方法
	SayHello(ctx context.Context, in *HelloHttpRequest, opts ...grpc.CallOption) (*HelloHttpReply, error)
}

type helloHttpClient struct {
	cc *grpc.ClientConn
}

func NewHelloHttpClient(cc *grpc.ClientConn) HelloHttpClient {
	return &helloHttpClient{cc}
}

func (c *helloHttpClient) SayHello(ctx context.Context, in *HelloHttpRequest, opts ...grpc.CallOption) (*HelloHttpReply, error) {
	out := new(HelloHttpReply)
	err := grpc.Invoke(ctx, "/proto.HelloHttp/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HelloHttp service

type HelloHttpServer interface {
	// 定义SayHello方法
	SayHello(context.Context, *HelloHttpRequest) (*HelloHttpReply, error)
}

func RegisterHelloHttpServer(s *grpc.Server, srv HelloHttpServer) {
	s.RegisterService(&_HelloHttp_serviceDesc, srv)
}

func _HelloHttp_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloHttpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloHttpServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.HelloHttp/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloHttpServer).SayHello(ctx, req.(*HelloHttpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HelloHttp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.HelloHttp",
	HandlerType: (*HelloHttpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HelloHttp_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello_http/hello_http.proto",
}

func init() { proto1.RegisterFile("hello_http/hello_http.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xce, 0x48, 0xcd, 0xc9,
	0xc9, 0x8f, 0xcf, 0x28, 0x29, 0x29, 0xd0, 0x47, 0x30, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85,
	0x58, 0xc1, 0x94, 0x94, 0x4c, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x7e, 0x62, 0x41, 0xa6, 0x7e,
	0x62, 0x5e, 0x5e, 0x7e, 0x49, 0x62, 0x49, 0x66, 0x7e, 0x5e, 0x31, 0x44, 0x91, 0x92, 0x1a, 0x97,
	0x80, 0x07, 0x48, 0xa3, 0x47, 0x49, 0x49, 0x41, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90,
	0x10, 0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad,
	0xa4, 0xc5, 0xc5, 0x87, 0xa4, 0xae, 0x20, 0xa7, 0x52, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb5, 0xb8,
	0x38, 0x31, 0x1d, 0xa6, 0x10, 0xc6, 0x35, 0x4a, 0xe4, 0xe2, 0x84, 0xab, 0x15, 0x0a, 0xe1, 0xe2,
	0x08, 0x4e, 0xac, 0x04, 0xf3, 0x85, 0xc4, 0x21, 0x96, 0xea, 0xa1, 0xdb, 0x28, 0x25, 0x8a, 0x29,
	0x51, 0x90, 0x53, 0xa9, 0x24, 0xd1, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x21, 0x25, 0x5e, 0xfd, 0xd4,
	0x8a, 0xc4, 0xdc, 0x82, 0x9c, 0x54, 0xfd, 0xd4, 0xe4, 0x8c, 0x7c, 0x2b, 0x46, 0xad, 0x24, 0x36,
	0xb0, 0x7a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x55, 0x98, 0x58, 0x01, 0x01, 0x00,
	0x00,
}
